---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Application'
Parameters:
  ArtifactsBucketName:
    Type: String
  ArtifactObjectKey:
    Type: String
Resources:
  Application:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: 'automation-for-the-people'
  ApplicationVersion:
    Type: 'AWS::ElasticBeanstalk::ApplicationVersion'
    DeletionPolicy: Retain # ensures that old versions are not deleted
    Properties:
      ApplicationName: !Ref Application
      SourceBundle: 
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: !Ref ArtifactObjectKey
Outputs:
  VersionLabel:
    Value: !Ref ApplicationVersion
